#config_version=5
##! mode: my_mode
# we will initially set the value to 0 when the machine starts up

##! mode: base
# in your base mode (modes/base/config/base.yaml)
variable_player:
  black_widow_shot_hit:
    score: 100
  s_right_gauntlet_ramp_opto_active:
    score: 1000
    potato: 1
  s_right_flipper_active:
    potato: -2

mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50


###################################### SHOTS PROFILE ######################################

shot_profiles:
  my_first_profile:
    states:
      - name: unlit  # step 1
        show: off
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: true

###################################### SHOTS ######################################

##! mode: base
shots:
  black_widow_shot:
    switch: s_black_widow_ramp_opto
    show_tokens:
      led: l_black_widow_arrow
    profile: my_first_profile
